# Generated by Django 2.2 on 2020-05-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('DELIVERED', 'DELIVERED')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('INDOOR', 'INDOOR'), ('OUTDOOR', 'OUTDOOR'), ('BOTH', 'BOTH')], max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_manufactured', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
