# Generated by Django 2.2 on 2020-06-03 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200604_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='logopic',
            new_name='logo_pic',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Customer'),
        ),
    ]
